name: ci-cd
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
           - name: transfering the data
             uses: actions/checkout@v4

           - name: ci
             run: mvn clean install
            


